### ISSUE TITLE
InputDriver$Builder.<init>(int)' is inaccessible to class ButtonInputDriver

### ISSUE THREAD

**Issue by robertoestivill** [androidthings/sample-button#1]
Just cloned the repository and followed the instructions.
The application crash as soon as the activity is launched.
Raspberry PI 3 - DP3

```
05-20 17:48:47.254 1771-1771/com.example.androidthings.button E/AndroidRuntime: FATAL EXCEPTION: main 
    Process: com.example.androidthings.button, PID: 1771
    java.lang.IllegalAccessError: Method 'void com.google.android.things.userdriver.InputDriver$Builder.<init>(int)' is inaccessible to class 'com.google.android.things.contrib.driver.button.ButtonInputDriver' (declaration of 'com.google.android.things.contrib.driver.button.ButtonInputDriver' appears in /data/app/com.example.androidthings.button-1/base.apk)
       at com.google.android.things.contrib.driver.button.ButtonInputDriver.build(ButtonInputDriver.java:98)
       at com.google.android.things.contrib.driver.button.ButtonInputDriver.register(ButtonInputDriver.java:82)
       at com.example.androidthings.button.ButtonActivity.onCreate(ButtonActivity.java:64)
       at android.app.Activity.performCreate(Activity.java:6662)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by mangini** [comment]
Update your board to DP4 (or checkout the sample commit right before the
update to dp4). The user driver API has changed in DP4 in an non backwards
compatible way and we've updated all samples and drivers. We will improve
the error message in the next release.

**Comment by mangini** [comment]
Update your board to DP4 (or checkout the sample commit right before the
update to dp4). The user driver API has changed in DP4 in an non backwards
compatible way and we've updated all samples and drivers. We will improve
the error message in the next release.



On May 20, 2017 10:53 AM, "Robert" <notifications@github.com> wrote:

Just cloned the repository and followed the instructions.
The application crash as soon as the activity is launched.
Raspberry PI 3 - DP3

05-20 17:48:47.254 1771-1771/com.example.androidthings.button
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androidthings.button, PID: 1771
    java.lang.IllegalAccessError: Method 'void
com.google.android.things.userdriver.InputDriver$Builder.<init>(int)'
is inaccessible to class
'com.google.android.things.contrib.driver.button.ButtonInputDriver'
(declaration of
'com.google.android.things.contrib.driver.button.ButtonInputDriver'
appears in /data/app/com.example.androidthings.button-1/base.apk)
       at com.google.android.things.contrib.driver.button.ButtonInputDriver.build(ButtonInputDriver.java:98)
       at com.google.android.things.contrib.driver.button.ButtonInputDriver.register(ButtonInputDriver.java:82)
       at com.example.androidthings.button.ButtonActivity.onCreate(ButtonActivity.java:64)
       at android.app.Activity.performCreate(Activity.java:6662)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/androidthings/sample-button/issues/1>, or mute the
thread

**Comment by robertoestivill** [comment]
Yep. That fixed it. I was not aware of the incompatibilities. Thanks.
