### ISSUE TITLE
Can't run this sample application

### ISSUE THREAD

**Issue by danilobertelli** [androidthings/sample-button#4]
I've just downloaded this Sample Application and I got:

```
09-22 12:15:07.270 2953-2953/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.androidthings.button, PID: 2953
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.androidthings.button/com.example.androidthings.button.ButtonActivity}: java.lang.SecurityException: Caller lacks required permission com.google.android.things.permission.MANAGE_INPUT_DRIVERS
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.SecurityException: Caller lacks required permission com.google.android.things.permission.MANAGE_INPUT_DRIVERS
                                                     at android.os.Parcel.readException(Parcel.java:1942)
                                                     at android.os.Parcel.readException(Parcel.java:1888)
                                                     at com.google.android.things.userdriver.IInputDriverService$Stub$Proxy.createInputDevice(IInputDriverService.java:140)
                                                     at com.google.android.things.userdriver.InputDriver.initialize(InputDriver.java:241)
                                                     at com.google.android.things.userdriver.InputDriverManager.addInputDriver(InputDriverManager.java:47)
                                                     at com.google.android.things.userdriver.UserDriverManager.registerInputDriver(UserDriverManager.java:83)
                                                     at com.google.android.things.contrib.driver.button.ButtonInputDriver.register(ButtonInputDriver.java:83)
                                                     at com.example.androidthings.button.ButtonActivity.onCreate(ButtonActivity.java:64)
                                                     at android.app.Activity.performCreate(Activity.java:6975)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-22 12:15:07.289 311-464/system_process W/ActivityManager:   Force finishing activity com.example.androidthings.button/.ButtonActivity

```

I checked the manifest file and the permission is there.

**Comment by jdkoren** [comment]
Hi @danilobertelli, please try rebooting the board and running the app again. There is a known issue that permissions are not granted immediately at install, but they will be granted on boot.

**Comment by danilobertelli** [comment]
Thanks @jdkoren it worked!
